apiVersion: apps/v1
kind: Deployment
metadata:
  name: peckpython
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginxmiami
        image: peckma/pythonmoment:90
        ports:
        - containerPort: 8080
