apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: python-webapp
        image: peckma/hello-virtualization:latest
        ports:
        - containerPort: 8080
